server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hua_culture_database?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: 990611
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.good_ghost.hua_culture.entity
#打印日志信息
logging:
  level:
    com.good_ghost.hua_culture: debug